version: '3.8'

services:
  app:
      build: .
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdatabase
        - SPRING_DATASOURCE_USERNAME=yourusername
        - SPRING_DATASOURCE_PASSWORD=yourpassword
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      depends_on:
        - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=curriculos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"